import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Swiphr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.cdnfonts.com/css/sf-pro-display"
          rel="stylesheet"
        />
      </Head>
      <body className="m-0 p-0">
        <div className="px-5 sm:p-0 sm:flex flex-row">
          <div className="sm:p-4 sm:pb-0 lg:p-6 lg:pb-0">
            <Navbar />
          </div>
          <div className="sm:p-4 sm:pb-0 lg:p-6 lg:pb-0">{children}</div>
        </div>
      </body>
    </html>
  );
}
